# Generated by Django 2.1.5 on 2019-02-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='mobileImage')),
                ('Brand', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Face_recognition', models.BooleanField(default=False)),
            ],
        ),
    ]
